const { chromium } = require('/root/.npm/_npx/e41f203b7505f1fb/node_modules/playwright-core');
const EXEC='/root/.cache/ms-playwright/chromium-1208/chrome-linux64/chrome';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
  const b=await chromium.launch({executablePath:EXEC,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
  const p=await b.newPage({viewport:{width:1280,height:720}});
  const errs=[]; p.on('pageerror',e=>errs.push('pageerror:'+e.message)); p.on('console',m=>{if(m.type()==='error')errs.push('console:'+m.text());});
  await p.goto('file://'+process.cwd()+'/cursed-clash.html',{waitUntil:'load'});
  await sleep(500);
  await p.keyboard.press('Enter'); await sleep(300); await p.keyboard.press('Enter'); await sleep(1600);
  await p.evaluate(()=>{ const C=window.CLASH; C.p2.ai=false; C.p1.x=260; C.p2.x=980; C.p1.dir=1; C.p2.vx=0; });
  const R={};
  const press=async k=>{ await p.keyboard.down(k); await sleep(80); await p.keyboard.up(k); };
  const st=()=>p.evaluate(()=>({state:window.CLASH.p1.state, superT:+window.CLASH.p1.superT.toFixed(2), proj:window.CLASH.projCount()}));
  await p.keyboard.down('KeyD'); await sleep(500);
  R.walk=await st(); await p.keyboard.up('KeyD'); await sleep(400);
  R.idle=await st();
  await press('KeyW'); await sleep(80); R.jump=await p.evaluate(()=>window.CLASH.p1.onGround===false);
  await sleep(700);
  await press('KeyJ'); await sleep(30); R.punch=(await st()).state;
  await sleep(400);
  await press('KeyK'); await sleep(40); R.kick=(await st()).state;
  await sleep(500);
  await p.keyboard.down('KeyL'); await sleep(80); R.block=(await st()).state; await p.keyboard.up('KeyL');
  await p.evaluate(()=>{ window.CLASH.p1.meter=100; window.CLASH.p1.atk=null; }); await sleep(60);
  await press('KeyI'); await sleep(120); R.super1=await st();
  await sleep(160); R.super2=await st();
  R.errs=errs;
  console.log(JSON.stringify(R,null,1));
  await b.close();
})().catch(e=>{console.error('FAIL',e.message);process.exit(1)});
